In [ ]:
from tensorflow.keras.preprocessing.text import  one_hot  

In [ ]:
# sentences
# The embedding layer converts each word index into a dense vector representation of fixed size.
sent=[" the glass of milk"
     ,'the glass of juice',
     'I am a good boy',
     'understand the meaning of words',
'your videos are good'
    ]

In [3]:
sent

[' the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [4]:
print(type(sent))

<class 'list'>


In [5]:
#define the vocabulary size
voc_size=10000

In [6]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6484, 6876, 900, 8585],
 [6484, 6876, 900, 6364],
 [5405, 1163, 9515, 3585, 4711],
 [5204, 6484, 7321, 900, 6949],
 [5064, 8800, 7850, 3585]]

[5724, 3464, 4103, 4729]=> the index of the words (the glass of milk) ie 5724-> the all other index will zero at that time 

In [ ]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import   pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
  

In [8]:
import numpy as np
sent_length=8 #max length of the sentence

In [9]:
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs#fixed length vector of 8 for each sentence

array([[   0,    0,    0,    0, 6484, 6876,  900, 8585],
       [   0,    0,    0,    0, 6484, 6876,  900, 6364],
       [   0,    0,    0, 5405, 1163, 9515, 3585, 4711],
       [   0,    0,    0, 5204, 6484, 7321,  900, 6949],
       [   0,    0,    0,    0, 5064, 8800, 7850, 3585]])

In [10]:
#feature dimension
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
# Each number → converted to a vector of size = dim (10)

c:\ML\00implimention\DL\01ANN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)  # converting words → vectors

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step


array([[[-0.03809853, -0.03599428,  0.03853932, -0.01364328,
          0.02103189,  0.03577494,  0.01684697,  0.01845359,
          0.01177604, -0.04312568],
        [-0.03809853, -0.03599428,  0.03853932, -0.01364328,
          0.02103189,  0.03577494,  0.01684697,  0.01845359,
          0.01177604, -0.04312568],
        [-0.03809853, -0.03599428,  0.03853932, -0.01364328,
          0.02103189,  0.03577494,  0.01684697,  0.01845359,
          0.01177604, -0.04312568],
        [-0.03809853, -0.03599428,  0.03853932, -0.01364328,
          0.02103189,  0.03577494,  0.01684697,  0.01845359,
          0.01177604, -0.04312568],
        [-0.0066252 ,  0.03483607, -0.0105425 , -0.03526897,
         -0.00291213, -0.04915712, -0.04410615, -0.02338948,
         -0.0105325 , -0.0365394 ],
        [-0.04255223,  0.04211674,  0.0060661 ,  0.03026542,
         -0.01048331, -0.02923443, -0.01515555, -0.0493183 ,
         -0.02214584,  0.00608423],
        [-0.02231443, -0.02210882,  0.01633601,  0.0

In [15]:
embedded_docs[0] # first sentence

array([   0,    0,    0,    0, 6484, 6876,  900, 8585])